services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883" #default MQTT port
      - "9001:9001" #default MQTT websocket port
    volumes:    
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/pwfile:/mosquitto/config/pwfile
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw

  orion-ld:
    image: fiware/orion-ld
    ports:
      - "1026:1026"
    depends_on:
      - mongo-db
    command: -dbhost mongo-db

  mongo-db:
    image: mongo:4.4
    command: --nojournal
    ports:
      - "27017:27017"
  
  quantumleap:
    image: orchestracities/quantumleap:0.8.0
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
    environment:
      - CRATE_HOST=crate-db

  crate-db:
    image: crate:latest
    ports:
      - "4200:4200"
      - "4300:4300"
      - "5432:5432"
  
  grafana:
    image: grafana/grafana
    depends_on:
        - crate-db
    ports:
      - "3000:3000"
    environment:
        - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel

  adminer:
    image: adminer
    restart: always
    depends_on:
      - crate-db
    ports:
      - 8080:8080


networks:
  default:
    name: shs-network