{
 "title": "HumiTemp Sensor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Current Values",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperature, time_index, humidity FROM etsensorreading WHERE entity_id = 'A0:DD:6C:10:8A:4C' ORDER BY time_index DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT temperature, time_index FROM etsensorreading WHERE entity_id = 'A0:DD:6C:10:8A:4C' ORDER BY time_index DESC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT humidity, time_index FROM etsensorreading WHERE entity_id = 'A0:DD:6C:10:8A:4C' ORDER BY time_index DESC"
    }
   ]
  }
 ]
}